services:
  - type: web
    name: miningusdt
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: MONGODB_URI
        value: mongodb+srv://kabusbaba:GpzqCqKyAlS6N7Kn@cluster0.zh0a3gc.mongodb.net/miningusdt?retryWrites=true&w=majority
